### ISSUE TITLE
Uncaught ReferenceError: cosmiconfig is not defined

### ISSUE THREAD

**Issue by cw6365** [1000ch/atom-jsfmt#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [jsfmt](https://github.com/1000ch/atom-jsfmt) package, v1.2.0
### Stack Trace

Uncaught ReferenceError: cosmiconfig is not defined

```
At /Users/chrisward/.atom/packages/jsfmt/index.js:41

ReferenceError: cosmiconfig is not defined
    at execute (/Users/chrisward/.atom/packages/jsfmt/index.js:41:3)
    at atom-workspace.<anonymous> (/Users/chrisward/.atom/packages/jsfmt/index.js:72:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/chrisward/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/chrisward/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/chrisward/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Users/chrisward/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Users/chrisward/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Users/chrisward/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/chrisward/Downloads/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Users/chrisward/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Users/chrisward/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:42.3.0 core:undo (atom-text-editor.editor.is-focused)
  2x -2:41.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:31 core:undo (atom-text-editor.editor.is-focused)
     -2:30 core:save (atom-text-editor.editor.is-focused)
     -2:28 core:undo (atom-text-editor.editor.is-focused)
     -2:13.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:09.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:08.0 settings-view:uninstall-packages (atom-text-editor.editor)
     -1:49.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:03.9.0 core:undo (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:54.5.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:52.8.0 core:save (atom-text-editor.editor.is-focused)
 18x -0:31 editor:move-to-next-subword-boundary (atom-text-editor.editor.is-focused)
     -0:01.0 jsfmt:execute (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
emmet, v2.4.2
jsfmt, v1.2.0
project-manager, v2.7.6

# Dev
No dev packages
```

**Comment by jeffreyfate** [comment]
I have the same issue

**Comment by 1000ch** [comment]
@cw6365 @jeffthefate Please update to `v1.3.0` 🙏
